### ISSUE TITLE
Minio uploading fails

### ISSUE THREAD

**Issue by LeagueRaINi** [stv0g/gose#23]
When trying to upload a file to a minio bucket i get `Upload failed: [object Object]` in gose and this in the minio traces
![raw](https://user-images.githubusercontent.com/19365835/172172588-f362768a-ecbe-4bf0-abd0-93475e9b36af.png)

<details>
  <summary>docker-compose.yml</summary>

  ```yaml
  version: '3.7'
  services:
    minio:
      image: minio/minio:RELEASE.2022-06-03T01-40-53Z.fips
      command: server /mnt/data --console-address ":9001"
      ports:
        - 8200:9000 # API
        - 8201:9001 # Webinterface
      environment:
        MINIO_ROOT_USER: "<redacted>"
        MINIO_ROOT_PASSWORD: "<redacted>"
        MINIO_SERVER_URL: "<redacted>"
        MINIO_SITE_REGION: "s3"
      volumes:
        - minio-data:/mnt/data
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
        interval: 30s
        timeout: 20s
        retries: 3
    gose:
      image: ghcr.io/stv0g/gose:v0.4.0
      ports:
        - 8203:8080
      command: -config /config.yml
      volumes:
        - ./config.yml:/config.yml
      #environment:
        #GOSE_LISTEN: ":8080"
        #GOSE_BASE_URL: "<redacted>"
        #GOSE_BUCKET: "gose-uploads"
        #GOSE_ENDPOINT: "minio:9000"
        #GOSE_REGION: "s3"
        #GOSE_PATH_STYLE: "true"
        #GOSE_NO_SSL: "true"
        #GOSE_ACCESS_KEY: "<redacted>" # MINIO_ROOT_USER
        #GOSE_SECRET_KEY: "<redacted>" # MINIO_ROOT_PASSWORD
        #GOSE_S3_MAX_UPLOAD_SIZE: "50GB"
        #GOSE_S3_PART_SIZE: "5MB"
        #GOSE_S3_EXPIRATION_DEFAULT_CLASS: "1week"
      depends_on: [ minio ]
  
  volumes:
    minio-data:
  ```
</details>

<details>
  <summary>config.yml</summary>

  ```yaml
  listen: ":8080"

  base_url: <redacted>

  max_upload_size: 50GB
  part_size: 5MB

  servers:
  - bucket: gose-uploads

    endpoint: minio:9000
    region: s3

    path_style: true
    no_ssl: true

    access_key: "<redacted>" # MINIO_ROOT_USER
    secret_key: "<redacted>" # MINIO_ROOT_PASSWORD

    create_bucket: true

    expiration:
    - id: 1day
      title: 1 day
      days: 1
    - id: 1week
      title: 1 week
      days: 7
    - id: 1month
      title: 1 month
      days: 31
    - id: 1year
      title: 1 year
      days: 365
  ```
</details>

passing the config settings as environment variables seems to not work as well, settings like the bucket and max_upload/part_size arent getting set for me thats why i'm using the config
