### ISSUE TITLE
upload error with minio s3

### ISSUE THREAD

**Issue by philippkayser** [stv0g/gose#38]
I try to upload a file with connected minio s3 bucket.

The file is visible in the bucket but the UI shows the following error. If you try it again with the same file it works fine.

"Upload failed: Failed API request: failed to tag object"
<img width="946" alt="image" src="https://user-images.githubusercontent.com/41049458/196303676-3abe9698-dd53-4a8d-90dd-a5abbe5ecfbc.png">

docker-compose.yml following:

```
version: "3.3"
services:
  gose:
    image: ghcr.io/stv0g/gose:v0.4.0
    build:
      context: .
    expose:
     - "8080"
    environment:
      GOSE_LISTEN: ":8080"
      GOSE_BASE_URL: "https://dropme.domain"
      GOSE_BUCKET: "dropme"
      GOSE_ENDPOINT: "s3.eu-central-2.wasabisys.com"
      GOSE_REGION: "eu-central-2"
      GOSE_PATH_STYLE: "true"
      GOSE_NO_SSL: "false"
      GOSE_ACCESS_KEY: "***********" # changeme!
      GOSE_SECRET_KEY: "************" # changeme!
      GOSE_MAX_UPLOAD_SIZE: "50GB"
      GOSE_PART_SIZE: "16MB"
      GOSE_SETUP_CORS: "false"
      GOSE_SETUP_BUCKET: "false"
      GOSE_SETUP_LIFECYCLE: "false"
    networks:
      - web
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:dropme.domain"
      - "traefik.port=8080"

networks:
 web:
    external: true
```
