### ISSUE TITLE
Trying to use Backblaze with gose -  Upload failed: [object Object]

### ISSUE THREAD

**Issue by Slopz** [stv0g/gose#42]
I don't know anything when it comes to cloud storage and gose, but I've trying to set up B2 with gose and I keep getting the "Upload failed: [object Object]" error when uploading a file. 

At first I had the error related to CORS and Lifecycle but managed to solve that, and now I'm stuck here. 

So I'm guessing Backblaze is not compatible despite its S3 compatible API? Probably missing some S3 features? 

Here's my compose in case I misconfigured it. 

```
---
version: "3.7" 
services:

  gose:
    image: ghcr.io/stv0g/gose:latest
    build:
      context: .
    ports:
    - 8087:8080
    environment:
      GOSE_LISTEN: ":8080"
      GOSE_BASE_URL: "http://localhost:8080"
      GOSE_BUCKET: "goseuploads"
      GOSE_ENDPOINT: "s3.eu-central-003.backblazeb2.com"
      GOSE_REGION: "eu-central-003"
      GOSE_PATH_STYLE: "true"
      GOSE_NO_SSL: "false"
      GOSE_ACCESS_KEY: "accesskeygoeshere"
      GOSE_SECRET_KEY: "secrectkeygoeshere"
      GOSE_MAX_UPLOAD_SIZE: "50GB"
      GOSE_PART_SIZE: "16MB"
      GOSE_SETUP_CORS: "false"
      GOSE_SETUP_LIFECYCLE: "false"

```

Thanks!
